base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name = 'home'),

    path('shop/', views.shop, name = 'shop'),
    path('shop/product/<pid>/', views.product, name = 'product'),
    path('category/<cid>/', views.categoryProduct, name = 'categoryProduct'),
    path('tag/<slug:tag_slug>/', views.tagList, name = 'tagList'),

    path('about/', views.about, name = 'about'),
    path('faq/', views.faq, name = 'faq'),
    path('blog/', views.blog, name = 'blog'),
    path('blog/single', views.showBlog, name = 'showBlog'),
    path('contact/', views.contact, name = 'contact'),

    path('dashboard/', views.userDashboard, name = 'userDashboard'),
    path('profile-edit/', views.userEditProfile, name = 'userEditProfile'),
    path('terms-and-conditions/', views.termsAndConditions, name = 'termsAndConditions'),

    path('vendors/', views.vendors, name = 'vendors'),
    path('vendors/<vid>', views.vendorView, name = 'vendorView'),

    path('user/', include('userauths.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('user/', include('userauths.urls')),
]

base/models.py
from pyexpat import model
from django.db import models
from shortuuidfield import ShortUUIDField
from django.utils.html import mark_safe
from userauths.models import CustomUser
from taggit.managers import TaggableManager

STATUS_CHOICES = (
	("process", "Processing"),
	("shipped", "Shipped"),
	("delivered", "Delivered"),
)

STATUS = (
	("draft", "Draft"),
	("disabled", "Disabled"),
	("rejected", "Rejected"),
	("in_review", "In Review"),
	("published", "Published"),
)

RATING = (
	(1, "⭐"),
	(2, "⭐⭐"),
	(3, "⭐⭐⭐"),
	(4, "⭐⭐⭐⭐"),
	(5, "⭐⭐⭐⭐⭐"),
)

def use_directory_path(instance, filename):
	return 'user_{0}/{1}'.format(instance.user.id, filename)

def validate_svg(value):
    """
    Validate that the uploaded file is an SVG.
    """
    if value.file.content_type != 'image/svg+xml':
        raise ValidationError("Only SVG files are allowed.")

class Category(models.Model):
    cid = ShortUUIDField(unique=True, max_length=20)
    title = models.CharField(max_length=100, default="Category Name")
    image = models.FileField(upload_to="category", default="category.jpg", validators=[validate_svg])

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        if self.image:
            # Get the content type of the uploaded file
            content_type = self.image.content_type
            # Adjust this part if you want to display the content type differently
            return mark_safe('<p>Content Type: %s</p><img src="%s" width="50" height="50" />' % (content_type, self.image.url))
        else:
            return "No image"

    def __str__(self):
        return self.title

class Vendor(models.Model):
	vid = ShortUUIDField(unique=True, max_length=20)

	title = models.CharField(max_length=100, default="John Doe")
	image = models.ImageField(upload_to=use_directory_path, default="vendor.jpg")
	description = models.TextField(null=True, blank=False, default="Vendor description here,.....")

	address = models.CharField(max_length=100, default="123 Kigali Rwanda")
	contact = models.CharField(max_length=100, default="123456789")
	chat_resp_time = models.CharField(max_length=100, default="100")
	shipping_on_time = models.CharField(max_length=100, default="100")
	authentic_rating = models.CharField(max_length=100, default="100")
	days_return = models.CharField(max_length=100, default="100")
	warranty_period = models.CharField(max_length=100, default="100")

	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

	class Meta:
		verbose_name_plural = "Vendors"

	def vendor_image(self):
		return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

	def __str__(self):
		return self.title

class Product(models.Model):
	pid = ShortUUIDField(unique=True, max_length=20)

	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
	vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, related_name="product")
	
	title = models.CharField(max_length=100, default="Product Title")
	image = models.ImageField(upload_to=use_directory_path, default="product.jpg")
	description = models.TextField(null=True, blank=False, default="This is the Product")

	price = models.DecimalField(max_digits=99999999999, decimal_places=2, default="1.99")
	old_price = models.DecimalField(max_digits=9999999999, decimal_places=2, default="2.99")

	specifications = models.TextField(null=True, blank=True)
	condition = models.CharField(max_length=100, default="Second Hand", null=True, blank=True)
	brand = models.CharField(max_length=100, default="Brand Name", null=True, blank=True)
	model = models.CharField(max_length=100, default="Model Name", null=True, blank=True)

	tags = TaggableManager(blank=True)

	product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

	status = models.BooleanField(default=True)
	in_stock = models.BooleanField(default=True)
	featured = models.BooleanField(default=True)
	digital = models.BooleanField(default=True)

	sku = ShortUUIDField(unique=True, max_length=10)

	date = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(null=True, blank=True)

	class Meta:
		verbose_name_plural = "Products"

	def product_image(self):
		return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

	def __str__(self):
		return self.title

	def get_percentage(self):
		new_price = (self.price / self.old_price) * 100

		return new_price

class ProductImages(models.Model):
	images = models.ImageField(upload_to="product-images", default="product.jpg")
	product = models.ForeignKey(Product, related_name = "p_images", on_delete=models.SET_NULL, null=True)
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Product Images"

class CartOrder(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=99999999999, decimal_places=2, default="1.99")
	paid_status = models.BooleanField(default=False)
	order_date = models.DateTimeField(auto_now_add=True)
	product_status = models.CharField(choices=STATUS_CHOICES, max_length=30, default="processing")

	class Meta:
		verbose_name_plural = "Cart Order"

class CartOrderItems(models.Model):
	order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
	invoice_no = models.CharField(max_length=200)
	product_status = models.CharField(max_length=200)
	item = models.CharField(max_length=200)
	image = models.CharField(max_length=200)
	qty = models.IntegerField(default=0)
	price = models.DecimalField(max_digits=99999999999, decimal_places=2, default=1.99)
	total = models.DecimalField(max_digits=99999999999, decimal_places=2, default=1.99)

	class Meta:
		verbose_name_plural = "Cart Order Items"

	def order_img(self):
		return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image.url))

class ProductReview(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	review = models.TextField()
	rating = models.IntegerField(choices=RATING, default=None)
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Product Reviews"

	def __str__(self):
		return self.product.title

	def get_rating(self):
		return self.rating

class Wishlist(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Wishlists"

	def __str__(self):
		return self.product.title

class Address(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=100, null=True)
	status = models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = "Address"

base/views.py
from django.shortcuts import render, get_object_or_404
from base.models import *
from taggit.models import Tag

def home(request):
	categories = Category.objects.all()
	products = Product.objects.filter(product_status="published", featured=True)

	context = {
		'categories': categories,
		'products': products
	}

	return render(request, 'index.html', context)

def about(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'about.html', context)

def shop(request):
	categories = Category.objects.all()
	products = Product.objects.order_by("-id")

	context = {
		'categories': categories,
		'products': products
	}

	return render(request, 'shop.html', context)

def product(request, pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)[:4]
    p_images = product.p_images.all()

    context = {
        'product': product,
        'products': products,
        'p_images': p_images
    }

    return render(request, 'product.html', context)

def categoryProduct(request, cid):
	category = Category.objects.get(cid=cid)
	products = Product.objects.filter(product_status="published", category=category)

	context = {
		'category': category,
		'products': products
	}

	return render(request, 'categoryProduct.html', context)

def tagList(request, tag_slug=None):
	products = Product.objects.filter(product_status="published").order_by("-id")

	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		products = products.filter(tags__in=[tag])

	context = {
		'products': products,
		'tag': tag
	}

	return render(request, 'tag.html', context)

def faq(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'faq.html', context)

def blog(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'blog.html', context)

def showBlog(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'blog-show.html', context)

def contact(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'contact.html', context)

def userDashboard(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'profile/dashboard.html', context)

def userEditProfile(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'profile/edit-profile.html', context)

def termsAndConditions(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'terms-and-conditions.html', context)

def vendors(request):
	vendors = Vendor.objects.all()

	context = {
		'vendors': vendors
	}

	return render(request, 'vendors/index.html', context)

def vendorView(request, vid):
	vendor = Vendor.objects.get(vid=vid)
	products = Product.objects.filter(vendor=vendor, product_status="published")

	context = {
		'vendor': vendor,
		'products': products,
	}

	return render(request, 'vendors/show.html', context)

base/templates/categoryProduct.html
{% extends 'layouts/app.html' %}
{% load static %}
{% block title %}{{ category.title }}{% endblock %} 
{% block content %}

    <div class="breadcrumbs">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">{{ category.title }} ({{ category.category.count }})</h1>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'base:home' %}">Home</a></li>
                        <li><a href="{% url 'base:shop' %}">Shop</a></li>
                        <li>{{ category.title }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <section class="category-page section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12">
                    <div class="category-grid-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-12">
                                <h3 style="font-size: 18px">We found <strong class="text-brand">{{ products.count }}</strong> item{{ products.count|pluralize }}</h3>
                            </div>
                            <div class="col-12">
                                <div class="tab-content" id="nav-tabContent">
                                    <div class="tab-pane fade show active" id="nav-grid" role="tabpanel"
                                        aria-labelledby="nav-grid-tab">
                                        <div class="row">
                                            {% for product in products %}
                                                <div class="col-lg-3 col-md-6 col-12">
                                                    <div class="single-item-grid">
                                                        <div class="image">
                                                            <a href="{% url 'base:product' product.pid %}"><img src="{{ product.image.url }}" alt="#"></a>
                                                            <i class=" cross-badge lni lni-bolt"></i>
                                                            <span class="flat-badge sale">{{ product.get_percentage|floatformat:0 }}%</span>
                                                        </div>
                                                        <div class="content">
                                                            <a href="javascript:void(0)" class="tag">{{ product.category.title }}</a>
                                                            <h3 class="title">
                                                                <a href="{% url 'base:product' product.pid %}">{{ product.title }}</a>
                                                            </h3>
                                                            <ul class="info">
                                                                <li class="price">${{ product.price }}</span></li>
                                                                <li class="like">
                                                                    <a href="javascript:void(0)">
                                                                        <i class="lni lni-heart"></i>
                                                                    </a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>

                                        <div class="row">
                                            <div class="col-12">
                                                <!-- Pagination -->
                                                <div class="pagination left">
                                                    <ul class="pagination-list">
                                                        <li><a href="javascript:void(0)">1</a></li>
                                                        <li class="active"><a href="javascript:void(0)">2</a></li>
                                                        <li><a href="javascript:void(0)">3</a></li>
                                                        <li><a href="javascript:void(0)">4</a></li>
                                                        <li><a href="javascript:void(0)"><i class="lni lni-chevron-right"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="tab-pane fade" id="nav-list" role="tabpanel" aria-labelledby="nav-list-tab">
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-12">
                                                {% for product in products %}
                                                    <div class="single-item-grid">
                                                        <div class="row align-items-center">
                                                            <div class="col-lg-5 col-md-7 col-12">
                                                                <div class="image">
                                                                    <a href="{% url 'base:product' product.pid %}"><img src="{{ product.image.url }}" alt="#"></a>
                                                                    <i class=" cross-badge lni lni-bolt"></i>
                                                                    <span class="flat-badge sale">Sale</span>
                                                                </div>
                                                            </div>
                                                            <div class="col-lg-7 col-md-5 col-12">
                                                                <div class="content">
                                                                    <a href="javascript:void(0)" class="tag">{{ product.category.title }}</a>
                                                                    <h3 class="title">
                                                                        <a href="{% url 'base:product' product.pid %}">{{ product.title }}</a>
                                                                    </h3>
                                                                    <ul class="info">
                                                                        <li class="price">{{ product.price }}</li>
                                                                        <li class="like"><a href="javascript:void(0)"><i class="lni lni-heart"></i></a>
                                                                        </li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12">
                                                <!-- Pagination -->
                                                <div class="pagination left">
                                                    <ul class="pagination-list">
                                                        <li><a href="javascript:void(0)">1</a></li>
                                                        <li class="active"><a href="javascript:void(0)">2</a></li>
                                                        <li><a href="javascript:void(0)">3</a></li>
                                                        <li><a href="javascript:void(0)">4</a></li>
                                                        <li><a href="javascript:void(0)"><i class="lni lni-chevron-right"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

base/templates/tag.html
{% extends 'layouts/app.html' %}
{% load static %}
{% block title %}{{ tag.name }}{% endblock %} 
{% block content %}

    <div class="breadcrumbs">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">#{{ tag.name }} ({{ products.count }})</h1>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'base:home' %}">Home</a></li>
                        <li><a href="{% url 'base:shop' %}">Shop</a></li>
                        <li>#{{ tag.name }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <section class="category-page section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12">
                    <div class="category-grid-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-12">
                                <h3 style="font-size: 18px">We found <strong class="text-brand">{{ products.count }}</strong> item{{ products.count|pluralize }}</h3>
                            </div>
                            <div class="col-12">
                                <div class="tab-content" id="nav-tabContent">
                                    <div class="tab-pane fade show active" id="nav-grid" role="tabpanel"
                                        aria-labelledby="nav-grid-tab">
                                        <div class="row">
                                            {% for product in products %}
                                                <div class="col-lg-3 col-md-6 col-12">
                                                    <div class="single-item-grid">
                                                        <div class="image">
                                                            <a href="{% url 'base:product' product.pid %}"><img src="{{ product.image.url }}" alt="#"></a>
                                                            <i class=" cross-badge lni lni-bolt"></i>
                                                            <span class="flat-badge sale">Sale</span>
                                                        </div>
                                                        <div class="content">
                                                            <a href="javascript:void(0)" class="tag">{{ product.tag.name }}</a>
                                                            <h3 class="title">
                                                                <a href="{% url 'base:product' product.pid %}">{{ product.title }}</a>
                                                            </h3>
                                                            <ul class="info">
                                                                <li class="price">${{ product.price }}</span></li>
                                                                <li class="like">
                                                                    <a href="javascript:void(0)">
                                                                        <i class="lni lni-heart"></i>
                                                                    </a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>

                                        <div class="row">
                                            <div class="col-12">
                                                <!-- Pagination -->
                                                <div class="pagination left">
                                                    <ul class="pagination-list">
                                                        <li><a href="javascript:void(0)">1</a></li>
                                                        <li class="active"><a href="javascript:void(0)">2</a></li>
                                                        <li><a href="javascript:void(0)">3</a></li>
                                                        <li><a href="javascript:void(0)">4</a></li>
                                                        <li><a href="javascript:void(0)"><i class="lni lni-chevron-right"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="tab-pane fade" id="nav-list" role="tabpanel" aria-labelledby="nav-list-tab">
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-12">
                                                {% for product in products %}
                                                    <div class="single-item-grid">
                                                        <div class="row align-items-center">
                                                            <div class="col-lg-5 col-md-7 col-12">
                                                                <div class="image">
                                                                    <a href="{% url 'base:product' product.pid %}"><img src="{{ product.image.url }}" alt="#"></a>
                                                                    <i class=" cross-badge lni lni-bolt"></i>
                                                                    <span class="flat-badge sale">Sale</span>
                                                                </div>
                                                            </div>
                                                            <div class="col-lg-7 col-md-5 col-12">
                                                                <div class="content">
                                                                    <a href="javascript:void(0)" class="tag">{{ product.tag.name }}</a>
                                                                    <h3 class="title">
                                                                        <a href="{% url 'base:product' product.pid %}">{{ product.title }}</a>
                                                                    </h3>
                                                                    <ul class="info">
                                                                        <li class="price">{{ product.price }}</li>
                                                                        <li class="like"><a href="javascript:void(0)"><i class="lni lni-heart"></i></a>
                                                                        </li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12">
                                                <!-- Pagination -->
                                                <div class="pagination left">
                                                    <ul class="pagination-list">
                                                        <li><a href="javascript:void(0)">1</a></li>
                                                        <li class="active"><a href="javascript:void(0)">2</a></li>
                                                        <li><a href="javascript:void(0)">3</a></li>
                                                        <li><a href="javascript:void(0)">4</a></li>
                                                        <li><a href="javascript:void(0)"><i class="lni lni-chevron-right"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

base/templates/terms-and-conditions.html
{% extends 'layouts/app.html' %}
{% block title %}Terms & Conditions{% endblock %} 
{% block content %}

	<div class="breadcrumbs">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Terms & Conditions</h1>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'base:home' %}">Home</a></li>
                        <li>Terms & Conditions</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}