base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name = 'home'),

    path('shop/', views.shop, name = 'shop'),
    path('shop/product/<pid>/', views.product, name = 'product'),
    path('category/<cid>/', views.categoryProduct, name = 'categoryProduct'),
    path('tag/<slug:tag_slug>/', views.tagList, name = 'tagList'),

    path('about/', views.about, name = 'about'),
    path('faq/', views.faq, name = 'faq'),
    path('blog/', views.blog, name = 'blog'),
    path('blog/single', views.showBlog, name = 'showBlog'),
    path('contact/', views.contact, name = 'contact'),

    path('dashboard/', views.userDashboard, name = 'userDashboard'),
    path('profile-edit/', views.userEditProfile, name = 'userEditProfile'),
    path('terms-and-conditions/', views.termsAndConditions, name = 'termsAndConditions'),

    path('vendors/', views.vendors, name = 'vendors'),
    path('vendors/<vid>', views.vendorView, name = 'vendorView'),

    path('user/', include('userauths.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('user/', include('userauths.urls')),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path('register/', views.user_register, name = 'register'),
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
]

base/models.py
from pyexpat import model
from django.db import models
from shortuuidfield import ShortUUIDField
from django.utils.html import mark_safe
from userauths.models import CustomUser
from taggit.managers import TaggableManager

STATUS_CHOICES = (
	("process", "Processing"),
	("shipped", "Shipped"),
	("delivered", "Delivered"),
)

STATUS = (
	("draft", "Draft"),
	("disabled", "Disabled"),
	("rejected", "Rejected"),
	("in_review", "In Review"),
	("published", "Published"),
)

RATING = (
	(1, "⭐"),
	(2, "⭐⭐"),
	(3, "⭐⭐⭐"),
	(4, "⭐⭐⭐⭐"),
	(5, "⭐⭐⭐⭐⭐"),
)

def use_directory_path(instance, filename):
	return 'user_{0}/{1}'.format(instance.user.id, filename)

def validate_svg(value):
    """
    Validate that the uploaded file is an SVG.
    """
    if value.file.content_type != 'image/svg+xml':
        raise ValidationError("Only SVG files are allowed.")

class Category(models.Model):
    cid = ShortUUIDField(unique=True, max_length=20)
    title = models.CharField(max_length=100, default="Category Name")
    image = models.FileField(upload_to="category", default="category.jpg", validators=[validate_svg])

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        if self.image:
            # Get the content type of the uploaded file
            content_type = self.image.content_type
            # Adjust this part if you want to display the content type differently
            return mark_safe('<p>Content Type: %s</p><img src="%s" width="50" height="50" />' % (content_type, self.image.url))
        else:
            return "No image"

    def __str__(self):
        return self.title

class Vendor(models.Model):
	vid = ShortUUIDField(unique=True, max_length=20)

	title = models.CharField(max_length=100, default="John Doe")
	image = models.ImageField(upload_to=use_directory_path, default="vendor.jpg")
	description = models.TextField(null=True, blank=False, default="Vendor description here,.....")

	address = models.CharField(max_length=100, default="123 Kigali Rwanda")
	contact = models.CharField(max_length=100, default="123456789")
	chat_resp_time = models.CharField(max_length=100, default="100")
	shipping_on_time = models.CharField(max_length=100, default="100")
	authentic_rating = models.CharField(max_length=100, default="100")
	days_return = models.CharField(max_length=100, default="100")
	warranty_period = models.CharField(max_length=100, default="100")

	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

	class Meta:
		verbose_name_plural = "Vendors"

	def vendor_image(self):
		return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

	def __str__(self):
		return self.title

class Product(models.Model):
	pid = ShortUUIDField(unique=True, max_length=20)

	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
	vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, related_name="product")
	
	title = models.CharField(max_length=100, default="Product Title")
	image = models.ImageField(upload_to=use_directory_path, default="product.jpg")
	description = models.TextField(null=True, blank=False, default="This is the Product")

	price = models.DecimalField(max_digits=99999999999, decimal_places=2, default="1.99")
	old_price = models.DecimalField(max_digits=9999999999, decimal_places=2, default="2.99")

	specifications = models.TextField(null=True, blank=True)
	condition = models.CharField(max_length=100, default="Second Hand", null=True, blank=True)
	brand = models.CharField(max_length=100, default="Brand Name", null=True, blank=True)
	model = models.CharField(max_length=100, default="Model Name", null=True, blank=True)

	tags = TaggableManager(blank=True)

	product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

	status = models.BooleanField(default=True)
	in_stock = models.BooleanField(default=True)
	featured = models.BooleanField(default=True)
	digital = models.BooleanField(default=True)

	sku = ShortUUIDField(unique=True, max_length=10)

	date = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(null=True, blank=True)

	class Meta:
		verbose_name_plural = "Products"

	def product_image(self):
		return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

	def __str__(self):
		return self.title

	def get_percentage(self):
		new_price = (self.price / self.old_price) * 100

		return new_price

class ProductImages(models.Model):
	images = models.ImageField(upload_to="product-images", default="product.jpg")
	product = models.ForeignKey(Product, related_name = "p_images", on_delete=models.SET_NULL, null=True)
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Product Images"

class CartOrder(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=99999999999, decimal_places=2, default="1.99")
	paid_status = models.BooleanField(default=False)
	order_date = models.DateTimeField(auto_now_add=True)
	product_status = models.CharField(choices=STATUS_CHOICES, max_length=30, default="processing")

	class Meta:
		verbose_name_plural = "Cart Order"

class CartOrderItems(models.Model):
	order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
	invoice_no = models.CharField(max_length=200)
	product_status = models.CharField(max_length=200)
	item = models.CharField(max_length=200)
	image = models.CharField(max_length=200)
	qty = models.IntegerField(default=0)
	price = models.DecimalField(max_digits=99999999999, decimal_places=2, default=1.99)
	total = models.DecimalField(max_digits=99999999999, decimal_places=2, default=1.99)

	class Meta:
		verbose_name_plural = "Cart Order Items"

	def order_img(self):
		return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image.url))

class ProductReview(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	review = models.TextField()
	rating = models.IntegerField(choices=RATING, default=None)
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Product Reviews"

	def __str__(self):
		return self.product.title

	def get_rating(self):
		return self.rating

class Wishlist(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Wishlists"

	def __str__(self):
		return self.product.title

class Address(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=100, null=True)
	status = models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = "Address"

base/views.py
from django.shortcuts import render, get_object_or_404
from base.models import *
from taggit.models import Tag

def home(request):
	categories = Category.objects.all()
	products = Product.objects.filter(product_status="published", featured=True)

	context = {
		'categories': categories,
		'products': products
	}

	return render(request, 'index.html', context)

def about(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'about.html', context)

def shop(request):
	categories = Category.objects.all()
	products = Product.objects.order_by("-id")

	context = {
		'categories': categories,
		'products': products
	}

	return render(request, 'shop.html', context)

def product(request, pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)[:4]
    p_images = product.p_images.all()

    context = {
        'product': product,
        'products': products,
        'p_images': p_images
    }

    return render(request, 'product.html', context)

def categoryProduct(request, cid):
	category = Category.objects.get(cid=cid)
	products = Product.objects.filter(product_status="published", category=category)

	context = {
		'category': category,
		'products': products
	}

	return render(request, 'categoryProduct.html', context)

def tagList(request, tag_slug=None):
	products = Product.objects.filter(product_status="published").order_by("-id")

	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		products = products.filter(tags__in=[tag])

	context = {
		'products': products,
		'tag': tag
	}

	return render(request, 'tag.html', context)

def faq(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'faq.html', context)

def blog(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'blog.html', context)

def showBlog(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'blog-show.html', context)

def contact(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'contact.html', context)

def userDashboard(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'profile/dashboard.html', context)

def userEditProfile(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'profile/edit-profile.html', context)

def termsAndConditions(request):
	categories = Category.objects.all()

	context = {
		'categories': categories
	}

	return render(request, 'terms-and-conditions.html', context)

def vendors(request):
	vendors = Vendor.objects.all()

	context = {
		'vendors': vendors
	}

	return render(request, 'vendors/index.html', context)

def vendorView(request, vid):
	vendor = Vendor.objects.get(vid=vid)
	products = Product.objects.filter(vendor=vendor, product_status="published")

	context = {
		'vendor': vendor,
		'products': products,
	}

	return render(request, 'vendors/show.html', context)

base/templates/inc/blog-sidebar.html
{% load static %}

<aside class="col-lg-4 col-md-5 col-12">
    <div class="sidebar blog-grid-page">
        <!-- Start Single Widget -->
        <div class="widget search-widget">
            <h5 class="widget-title"><span>Search This Site</span></h5>
            <form action="#">
                <input type="text" placeholder="Search Here...">
                <button type="submit"><i class="lni lni-search-alt"></i></button>
            </form>
        </div>
        <!-- End Single Widget -->
        <!-- Start Single Widget -->
        <div class="widget popular-feeds">
            <h5 class="widget-title"><span>Popular Feeds</span></h5>
            <div class="popular-feed-loop">
                <div class="single-popular-feed">
                    <div class="feed-desc">
                        <h6 class="post-title"><a href="javascript:void(0)">Tips to write an impressive resume online for
                                beginner</a></h6>
                        <span class="time"><i class="lni lni-calendar"></i> 05th Nov 2023</span>
                    </div>
                </div>
                <div class="single-popular-feed">
                    <div class="feed-desc">
                        <h6 class="post-title"><a href="javascript:void(0)">10 most important SEO focus areas for
                                colleges
                                and universities</a></h6>
                        <span class="time"><i class="lni lni-calendar"></i> 24th March 2023</span>
                    </div>
                </div>
                <div class="single-popular-feed">
                    <div class="feed-desc">
                        <h6 class="post-title"><a href="javascript:void(0)">7 things you should never say to your boss in
                                your joblife</a></h6>
                        <span class="time"><i class="lni lni-calendar"></i> 30th Jan 2023</span>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Single Widget -->
        <!-- Start Single Widget -->
        <div class="widget categories-widget">
            <h5 class="widget-title"><span>Categories</span></h5>
            <ul class="custom">
                <li>
                    <a href="javascript:void(0)">Hotel & Travels<span>26</span></a>
                </li>
                <li>
                    <a href="javascript:void(0)">Services <span>30</span></a>
                </li>
                <li>
                    <a href="javascript:void(0)">Pets <span>71</span></a>
                </li>
                <li>
                    <a href="javascript:void(0)">Restaurants <span>56</span></a>
                </li>
                <li>
                    <a href="javascript:void(0)">Real Estate<span>15</span></a>
                </li>
                <li>
                    <a href="javascript:void(0)">Jobs <span>12</span></a>
                </li>
                <li>
                    <a href="javascript:void(0)">Electronics <span>17</span></a>
                </li>
            </ul>
        </div>
        <!-- End Single Widget -->
        <!-- Start Single Widget -->
        <div class="widget popular-tag-widget">
            <h5 class="widget-title"><span>Popular Tags</span></h5>
            <div class="tags">
                <a href="javascript:void(0)">Jobpress</a>
                <a href="javascript:void(0)">Design</a>
                <a href="javascript:void(0)">HR</a>
                <a href="javascript:void(0)">Recruiter</a>
                <a href="javascript:void(0)">Interview</a>
                <a href="javascript:void(0)">Employee</a>
                <a href="javascript:void(0)">Labor</a>
                <a href="javascript:void(0)">Salary</a>
                <a href="javascript:void(0)">Consult</a>
                <a href="javascript:void(0)">Business</a>
                <a href="javascript:void(0)">Candidates</a>
            </div>
        </div>
        <div class="widget sidebar-as">
            <h5 class="widget-title"><span>Advertisement</span></h5>
            <a href="javascript:void(0)">
                <img src="{% static 'images/banner/banner.jpg' %}" alt="#">
            </a>
        </div>
    </div>
</aside>

base/templates/inc/clients.html
{% load static %}

<div class="client-logo-section">
    <div class="container">
        <div class="client-logo-wrapper">
            <div class="client-logo-carousel d-flex align-items-center justify-content-between">
                <div class="client-logo">
                    <img src="{% static 'images/clients/client1.svg' %}" alt="#">
                </div>
                <div class="client-logo">
                    <img src="{% static 'images/clients/client2.svg' %}" alt="#">
                </div>
                <div class="client-logo">
                    <img src="{% static 'images/clients/client3.svg' %}" alt="#">
                </div>
                <div class="client-logo">
                    <img src="{% static 'images/clients/client4.svg' %}" alt="#">
                </div>
                <div class="client-logo">
                    <img src="{% static 'images/clients/client5.svg' %}" alt="#">
                </div>
                <div class="client-logo">
                    <img src="{% static 'images/clients/client2.svg' %}" alt="#">
                </div>
                <div class="client-logo">
                    <img src="{% static 'images/clients/client3.svg' %}" alt="#">
                </div>
                <div class="client-logo">
                    <img src="{% static 'images/clients/client4.svg' %}" alt="#">
                </div>
                <div class="client-logo">
                    <img src="{% static 'images/clients/client5.svg' %}" alt="#">
                </div>
            </div>
        </div>
    </div>
</div>

base/templates/inc/header.html
{% load static %}

<header class="header navbar-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <div class="nav-inner">
                    <nav class="navbar navbar-expand-lg">
                        <a class="navbar-brand" href="{% url 'base:home' %}">
                            <img src="{% static 'images/logo/logo.svg' %}" alt="Logo">
                        </a>
                        <button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                            <ul id="nav" class="navbar-nav ms-auto">
                                <li class="nav-item active">
                                    <a href="{% url 'base:home' %}" aria-label="Toggle navigation">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'base:about' %}" aria-label="Toggle navigation">About Us</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'base:shop' %}" aria-label="Toggle navigation">Shop</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'base:vendors' %}" aria-label="Toggle navigation">Vendors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dd-menu collapsed" href="javascript:void(0)" data-bs-toggle="collapse" data-bs-target="#submenu-1-3" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">Categories</a>
                                    <ul class="sub-menu collapse" id="submenu-1-3">
                                        {% for category in categories %}
                                            <li class="nav-item"><a href="{% url 'base:categoryProduct' category.cid %}">{{ category.title }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'base:faq' %}" aria-label="Toggle navigation">FAQs</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'base:blog' %}" aria-label="Toggle navigation">Blog</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'base:contact' %}" aria-label="Toggle navigation">Contact Us</a>
                                </li>
                            </ul>
                        </div>
                        <div class="login-button">
                            <ul>
                                {% if user.is_authenticated %}
                                    <li class="button header-button">
                                        <a href="{% url 'base:userDashboard' %}" class="btn button header-button text-white">Profile</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'userauths:logout' %}"><i class="lni lni-exit"></i> Logout</a>
                                    </li>
                                {% else %}
                                    <li>
                                        <a href="{% url 'userauths:login' %}"><i class="lni lni-enter"></i> Login</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'userauths:register' %}"><i class="lni lni-user"></i> Register</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </nav>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}}">
                                <span>{{ message }}</span>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <script>
                        setTimeout (() => {
                            $(".alert").alert("close");
                        })
                    </script>
                </div>
            </div>
        </div>
    </div>
</header>

base/templates/inc/newsletter.html
<div class="newsletter section">
    <div class="container">
        <div class="inner-content">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="title">
                        <i class="lni lni-alarm"></i>
                        <h2>Newsletter</h2>
                        <p>We don't send spam so don't worry.</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="form">
                        <form action="#" method="get" target="_blank" class="newsletter-form">
                            <input name="email" placeholder="Your email address" type="email">
                            <div class="button">
                                <button class="btn">Subscribe<span class="dir-part"></span></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

base/templates/inc/shop-sidebar.html
{% load static %}

<div class="col-lg-3 col-md-4 col-12">
    <div class="category-sidebar">
        <!-- Start Single Widget -->
        <div class="single-widget search">
            <h3>Search Ads</h3>
            <form action="#">
                <input type="text" placeholder="Search Here...">
                <button type="submit"><i class="lni lni-search-alt"></i></button>
            </form>
        </div>
        <!-- End Single Widget -->
        <!-- Start Single Widget -->
        <div class="single-widget">
            <h3>All Categories</h3>
            <ul class="list">
                {% for category in categories %}
                    <li>
                        <a href="{% url 'base:categoryProduct' category.cid %}">
                            <img src="{{ category.image.url }}" style="width: 20px;">
                            {{ category.title }}<span>{{ category.category.count }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <!-- End Single Widget -->
        <!-- Start Single Widget -->
        <div class="single-widget range">
            <h3>Price Range</h3>
            <input type="range" class="form-range" name="range" step="1" min="100" max="10000" value="10" onchange="rangePrimary.value=value">
            <div class="range-inner">
                <label>$</label>
                <input type="text" id="rangePrimary" placeholder="100" />
            </div>
        </div>
        <!-- End Single Widget -->
        <!-- Start Single Widget -->
        <div class="single-widget condition">
            <h3>Condition</h3>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault1">
                <label class="form-check-label" for="flexCheckDefault1">
                    All
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault2">
                <label class="form-check-label" for="flexCheckDefault2">
                    New
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault3">
                <label class="form-check-label" for="flexCheckDefault3">
                    Used
                </label>
            </div>
        </div>
        <!-- End Single Widget -->
        <!-- Start Single Widget -->
        <div class="single-widget banner">
            <h3>Advertisement</h3>
            <a href="javascript:void(0)">
                <img src="{% static 'images/banner/banner.jpg' %}" alt="#">
            </a>
        </div>
        <!-- End Single Widget -->
    </div>
</div>

base/templates/inc/testimonials.html
{% load static %}

<section class="testimonials section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title align-center gray-bg">
                    <h2 class="wow fadeInUp" data-wow-delay=".4s">What People Say</h2>
                    <p class="wow fadeInUp" data-wow-delay=".6s">There are many variations of passages of Lorem
                        Ipsum available, but the majority have suffered alteration in some form.</p>
                </div>
            </div>
        </div>
        <div class="row testimonial-slider">
            <div class="col-lg-4 col-md-6 col-12">
                <!-- Start Single Testimonial -->
                <div class="single-testimonial">
                    <div class="quote-icon">
                        <i class="lni lni-quotation"></i>
                    </div>
                    <div class="author">
                        <img src="{% static 'images/testimonial/testi1.jpg' %}" alt="#">
                        <h4 class="name">
                            Jane Anderson
                            <span class="deg">Founder & CEO</span>
                        </h4>
                    </div>
                    <div class="text">
                        <p>"It’s amazing how much easier it has been to meet new people and create instant
                            connections. I have the exact same personality, the only thing that has changed is my
                            mindset and a few behaviors."</p>
                    </div>
                </div>
                <!-- End Single Testimonial -->
            </div>
        </div>
    </div>
</section>

base/templates/inc/user-sidebar.html
{% load static %}

<div class="col-lg-3 col-md-4 col-12">
    <div class="dashboard-sidebar">
        <div class="user-image">
            <img src="{% static 'images/dashboard/user-image.jpg' %}" alt="#">
            <h3>Steve Aldridge
                <span><a href="javascript:void(0)">@username</a></span>
            </h3>
        </div>
        <div class="dashboard-menu">
            <ul>
                <li>
                    <a class="" href="{% url 'base:userDashboard' %}">
                        <i class="lni lni-dashboard"></i>
                        Dashboard
                    </a>
                </li>
                <li>
                    <a href="{% url 'base:userEditProfile' %}">
                        <i class="lni lni-dashboard"></i>
                        Edit Profile
                    </a>
                </li>
            </ul>
            <div class="button">
                <a class="btn" href="{% url 'base:userauths:logout' %}">Logout</a>
            </div>
        </div>
    </div>
</div>